#!/usr/bin/env sh
export PATH="$PATH:./node_modules/.bin"

echo 'running pre commit scripts'

echo 'starting to format the code'
npm run format

echo 'linting the code'
npm run lint:fix

echo 'pre commit scripts finished'
